(async function(){
 const out=document.getElementById('homeHotelResults'); if(!out)return;
 const q=document.getElementById('homeHotelSearch'), city=document.getElementById('homeHotelCity'), stars=document.getElementById('homeHotelStars');
 try{
  const data=await (await fetch('/hotels-data.json',{cache:'no-store'})).json();
  const media=await (await fetch('/hotels-media.json',{cache:'no-store'})).json().catch(()=>({}));
  const fallbacks={'شرم الشيخ':'https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=900&q=80','الغردقة':'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=900&q=80','دهب':'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80','مرسى علم':'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=900&q=80','العين السخنة':'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=80','طابا':'https://images.unsplash.com/photo-1470214304380-aadaedcfff1b?auto=format&fit=crop&w=900&q=80','الساحل الشمالي':'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80','سيوة':'https://images.unsplash.com/photo-1470214304380-aadaedcfff1b?auto=format&fit=crop&w=900&q=80'};
  const rows=[]; Object.entries(data).forEach(([destination,list])=>(list||[]).forEach(x=>{const m=media[x[0]]||{};rows.push({destination,name:x[0],stars:x[1],img:x[2]||m.image||fallbacks[destination],desc:x[3]||m.description||'',ar:x[4]||m.arabicName||''})}));
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function render(){const term=(q?.value||'').trim().toLowerCase(),c=city?.value||'',st=stars?.value||'';const hit=rows.filter(x=>(!term||[x.name,x.ar,x.destination,x.desc].join(' ').toLowerCase().includes(term))&&(!c||x.destination===c)&&(!st||String(x.stars)===st));const shown=hit.slice(0,8);out.innerHTML=shown.length?shown.map(x=>`<article class="ota-card"><img src="${esc(x.img||fallbacks[x.destination])}" alt="${esc(x.ar||x.name)}" loading="lazy" onerror="this.onerror=null;this.src='${esc(fallbacks[x.destination]||fallbacks['الغردقة'])}'"><div><span class="ota-badge">${esc(x.destination)}</span><h3>${esc(x.ar||x.name)}</h3><p>${esc(x.name)}</p><p>${x.stars?`${esc(x.stars)}★ · `:''}${esc(x.desc).slice(0,150)}</p></div><a class="ota-btn gold" href="destinations.html#${({'شرم الشيخ':'sharm-el-sheikh','الغردقة':'hurghada','دهب':'dahab','مرسى علم':'marsa-alam','العين السخنة':'ain-sokhna','طابا':'taba','الساحل الشمالي':'north-coast','سيوة':'siwa-oasis'}[x.destination]||'')}">التفاصيل</a></article>`).join(''):`<p>لا توجد نتائج مطابقة.</p>`;if(hit.length>8)out.insertAdjacentHTML('beforeend',`<p class="ota-search-note">يعرض البحث أول 8 نتائج من أصل ${hit.length}. افتح صفحة الوجهة للقائمة الكاملة.</p>`)}
  [q,city,stars].filter(Boolean).forEach(el=>el.addEventListener('input',render));render();
 }catch(e){out.innerHTML='<p>تعذر تحميل الفنادق حاليًا.</p>'}
})();
